### ISSUE TITLE
SSL error

### ISSUE THREAD

**Issue by anondev-sudo** [afnan007a/Ptero-vm-v2#9]
![image](https://user-images.githubusercontent.com/85408287/137357638-db5e7af9-1f91-48ad-a316-e2fb1b622662.png)

**Comment by afnan007a** [comment]
Hey thanks for reporting, I think it's because of we changed the host of the pterovm file so it messedup the curl, I will fix it asap

**Comment by anondev-sudo** [comment]
@afnan007a How I can reach you on Discord. I need help with hosting pterodactyl wings on ptero-vm.

**Comment by anondev-sudo** [comment]
When I want to start wings:
![](https://media.discordapp.net/attachments/749458500194664508/898959527280533504/unknown.png)

![](https://media.discordapp.net/attachments/749458500194664508/898959572352528455/unknown.png)
How to change hostname to some valid one?




Why is docker inactive?
![](https://media.discordapp.net/attachments/749458500194664508/898961060088930304/unknown.png)


I need help with running pterodactyl wings

**Comment by afnan007a** [comment]
u know u cant run wings inside wings because docker will have issues

**Comment by anondev-sudo** [comment]
So why you have written this here: 
![image](https://user-images.githubusercontent.com/85408287/137746142-80e7883a-b858-4c64-b78a-78cf276dcefe.png)
